- name: Rodar Gitleaks manualmente
  run: |
    curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
    chmod +x gitleaks
    ./gitleaks detect --source . --redact --verbose --log-level=debug --exit-code=1


