name: Verificação de segredos com Gitleaks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Rodar Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "--verbose --redact"
